# -*- mode: python -*-
Import('env')

e = env.Clone(LIBS = Split('boost_unit_test_framework-mt egen'), LIBPATH='#egen')

testprog = e.Program('libegen-test',
                     Split('main.cpp TestEquality.cpp TestInvalid.cpp TestPoint.cpp'))
e.AddPostAction(testprog, 'LD_LIBRARY_PATH=egen test/libegen-test')

env.Alias("build", testprog)
